### ISSUE TITLE
Why the defaults values?

### ISSUE THREAD

**Issue by eirc** [anapsix/zabbix-haproxy#11]
I do not understand why you have included a way to get default values for metrics we can not get. I get that seeing these impossible values would prompt one to fix them but wouldn't just leaving them empty do the same thing? Zabbix will change metrics with no values to "not supported" status so maybe this has something to do with this?

**Comment by eirc** [comment]
I also saw the branch that changes the defaults from 9999... to 0, was that a way to save graphs from over-stretching to fit the huge number? Still the same issue applies though, why can't you just leave them empty?

**Comment by anapsix** [comment]
Hey @eirc, good question.. Personally, agree that if the value is not available, it should not be returned..
The default values were introduced by @noamik and I just left them there at first, since no one complained :). Later, to have an ability to customize them at will.. If you put "@" as default into [MAP variable in haproxy_stats.sh](https://github.com/anapsix/zabbix-haproxy/blob/master/haproxy_stats.sh#L71), it will return an actual value.. (that's what I do in my private setup)

**Comment by noamik** [comment]
The reason I introduced default values was that I had trouble with zabbix if things returned unsupported. Unfortunatelly my memory fails to remember the exact kind of problem that occured. I think I recall issues with bulk transmit, but that can be complete bogus as well. I had to stop working on it before I got everything pieced together as neatly as I would have liked it to be. I still hope to have time to get back to this one day, but I see no timeslot for this in the next few months.

And of course: if you can get everything working without default values that's the way to go ...

**Comment by anapsix** [comment]
Thanks for the comment @noamik.
As I've mentioned, @eirc - you can update your MAP with custom defaults or use '@' to get exact values

**Comment by eirc** [comment]
Already did that :D We're preparing a couple of HAProxy servers with a kinda big configuration which means lots of items will be monitored so I'll get back to you if there are indeed issues with removing the default values. If anything it will be useful to at least have the reason the defaulting is needed documented.
