### ISSUE TITLE
Specify the discovery

### ISSUE THREAD

**Issue by NiwanetSupport** [anapsix/zabbix-haproxy#42]
Hi, it's me again !

Your script is still working very well but I do have a question.
Your script collect and send everything that he finds, couldn't it be possible to select specifics elements in order to not end up with 1000 per host? :)
Can you give me a clue about it? Do you think It is something "easy" to do?

Regards

**Comment by noamik** [comment]
Why don't you just disable all the values you don't need? Or even better: you could shorten their life time so you still have them but they don't take that much memory in the long run.

It's not so easy to not send them in the first place because they aren't queried one by one but all at once from haproxy. Since the zabbix template takes the value from an array based on their position you can't easily not send them. You would have to adjust the template as well for that which is errorprone. If you don't need some values, just disable them in your template. Sending them doesn't use much resources and you don't have to process them in the server if you don't need them.

**Comment by NiwanetSupport** [comment]
Thanks for your response, I think I will only disable the elements that I don't need.
